CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Models/ApplicationBdContext.cs
using CategoryCRUD_31.Models.Domain;
using Microsoft.EntityFrameworkCore;

namespace CategoryCRUD_31.Models
{
	public class ApplicationBdContext : DbContext
	{
		public ApplicationBdContext(DbContextOptions options) : base(options)
		{
			//
		}
		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			base.OnConfiguring(optionsBuilder);
		}

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);
		}

		public DbSet<Category> categorys { get; set; }
	}
}

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Models/Domain/Category.cs
using CategoryCRUD_31.Binders;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace CategoryCRUD_31.Models.Domain
{
	public class Category
	{
		[Key]
		public int CategoryMasterId { get; set; }

		[StringLength(50)]
		[Required(ErrorMessage = "入力してください。")]
		[ModelBinder(BinderType = typeof(CategoryNameBinding))]
		public string CategoryName { get; set; }
	}
}

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Models/ViewModels/AddCategoryViewModel.cs
using CategoryCRUD_31.Binders;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace CategoryCRUD_31.Models.ViewModels
{
	public class AddCategoryViewModel
	{

		public int CategoryMasterId { get; set; }


		[StringLength(50)]
		[Required(ErrorMessage = "入力してください。")]
		[ModelBinder(BinderType = typeof(CategoryNameBinding))]
		public string CategoryName { get; set; }
	}
}

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Pages/CategoryCRUD/AddCategory.cshtml.cs
using CategoryCRUD_31.Models.Domain;
using CategoryCRUD_31.Models.ViewModels;
using CategoryCRUD_31.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CategoryCRUD_31.Pages.CategoryCRUD
{
    public class AddCategoryModel : PageModel
    {
        private readonly ApplicationBdContext _context;

        public AddCategoryModel(ApplicationBdContext context)
        {
            _context = context;
        }
        [BindProperty]
        public AddCategoryViewModel CategoryRequest { get; set; }

        public void OnGet()
        {
        }

        public IActionResult OnPostAdd()
        {
            var CategoryDomainModel = new Category
            {
                CategoryName = CategoryRequest.CategoryName,
            };
            _context.categorys.Add(CategoryDomainModel);
            _context.SaveChanges();
            return RedirectToPage("/CategoryCRUD/AddSuccess");
        }
    }
}

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Pages/CategoryCRUD/AddSuccess.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CategoryCRUD_31.Pages.CategoryCRUD
{
    public class AddSuccessModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Pages/CategoryCRUD/Edit.cshtml.cs
using CategoryCRUD_31.Models.ViewModels;
using CategoryCRUD_31.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CategoryCRUD_31.Pages.CategoryCRUD
{
	public class EditModel : PageModel
	{
		private readonly ApplicationBdContext _context;

		[BindProperty]
		public AddCategoryViewModel AddCategoryViewModel { get; set; }

		public EditModel(ApplicationBdContext context)
		{
			_context = context;
		}
		public IActionResult OnGet(int CategoryMasterId)
		{
			var category = _context.categorys.Find(CategoryMasterId);

			if (category != null)

			{
				AddCategoryViewModel = new AddCategoryViewModel()
				{
					CategoryMasterId = category.CategoryMasterId,
					CategoryName = category.CategoryName
				};

			}
			else
			{
				return Content("khong co category nao");
			}
			return Page();
		}
		public IActionResult OnPostEdit()
		{
			if (AddCategoryViewModel != null)
			{
				var existingcategory = _context.categorys.Find(AddCategoryViewModel.CategoryMasterId);

				if (existingcategory != null)
				{
					{
						existingcategory.CategoryMasterId = AddCategoryViewModel.CategoryMasterId;
						existingcategory.CategoryName = AddCategoryViewModel.CategoryName;
						_context.SaveChanges();

                        return RedirectToPage("/CategoryCRUD/EditSuccess");

                    }

				}

			}
			return Page();
;		}
	}
}

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Pages/CategoryCRUD/EditSuccess.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CategoryCRUD_31.Pages.CategoryCRUD
{
    public class EditSuccessModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Pages/CategoryCRUD/List.cshtml.cs
using CategoryCRUD_31.Models;
using CategoryCRUD_31.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace CategoryCRUD_31.Pages.CategoryCRUD
{
    public class ListModel : PageModel
    {
        private readonly ApplicationBdContext _context;
        public List<CategoryCRUD_31.Models.Domain.Category> Categories { get; set; }

        [BindProperty]
        public AddCategoryViewModel AddCategoryViewModel { get; set; }

		public ListModel(ApplicationBdContext context)
        {
            _context = context;
        }


		public const int Item_Page = 3;


        [BindProperty(SupportsGet = true,Name ="p")]
		public int currentPage { set; get; }

		public int countPage { set; get; }
		public async Task OnGetAsync(string SearchCategoryname)
        {
            int totalCategory = await _context.categorys.CountAsync();

			countPage = (int)Math.Ceiling((double)totalCategory / Item_Page);

            if(currentPage < 1)
            {
                currentPage = 1;
            }
            if(currentPage > countPage)
            {
                currentPage = countPage;
            }

            var qr = (from a in _context.categorys
                     orderby a.CategoryName descending
                     select a)
                     .Skip((currentPage - 1) * Item_Page)
                     .Take(Item_Page);
            if (!string.IsNullOrEmpty(SearchCategoryname))
            {
                Categories = qr.Where(a => a.CategoryName.Contains(SearchCategoryname)).ToList();
            }
            else
            {
                Categories = await qr.ToListAsync();
			}

        }

        public async Task<IActionResult> OnPostDeleteAsync()
        {
            if (AddCategoryViewModel != null)
            {
                var existingCategory = await _context.categorys.FindAsync(AddCategoryViewModel.CategoryMasterId);
                if (existingCategory != null)
                {
                    _context.categorys.Remove(existingCategory);
                    await _context.SaveChangesAsync();
                }
            }

            return RedirectToPage("./List");
        }
    }
}

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace CategoryCRUD_31.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	[IgnoreAntiforgeryToken]
	public class ErrorModel : PageModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CategoryCRUD_31.Pages
{
	public class IndexModel : PageModel
	{
		private readonly ILogger<IndexModel> _logger;

		public IndexModel(ILogger<IndexModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{

		}
	}
}

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CategoryCRUD_31.Pages
{
	public class PrivacyModel : PageModel
	{
		private readonly ILogger<PrivacyModel> _logger;

		public PrivacyModel(ILogger<PrivacyModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
		}
	}
}

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Pages/CategoryCRUD/AddCategory.cshtml
@page
@model AddCategoryModel
@{
}
<h3 class="mb-5 mt-5" id="txtTitle"> 施策カテゴリ追加 </h3>
<div class="mb-5 mt-5" id="txtTitle1" style="display:none">
	<h3>施策カテゴリ追加</h3><br>
	<h3>以下の施策カテゴリを登録しますか？</h3>
</div>
<form method="post" asp-page="AddCategory" id="confirm">

	<div class="mb-3 mt-5 row">
		<label class="col-form-label col-sm-2">カテゴリー名</label>
		<div class="col-sm-8">
			<input class="form-control" id="txtName" asp-for="@Model.CategoryRequest.CategoryName" aria-required="true" />
			<span asp-validation-for="@Model.CategoryRequest.CategoryName" class="text-danger"></span>
			<label class="lblCatName" id="lblCatName"></label>
		</div>
	</div>

	<div class="col-sm-12 d-flex justify-content-around mt-2">

		<button class="btn btn-primary" type="button" id="btnback" style="display:none">戻る</button>
		<button class="btn btn-primary" type="submit" id="btnSubmit" style="display:none" asp-page-handler="Add">保存</button>
		<button class="btn btn-primary" type="button" id="btnback1" onclick="window.location.href ='/CategoryCRUD/list'">戻る</button>
		<button class="btn btn-primary" type="button" id="btnConfirm">確認</button>
	</div>

</form>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script type="text/javascript">
	$(document).ready(function () {
		//khoi tao bien local
		var catName;
		$("#btnConfirm").click(function (event) {
			var isValid = $("#confirm").valid()
			if (!isValid) {
				event.preventdefault();


			}
			else {
				//gan gia tri cho bien category Name
				catName = $("#txtName").val();
				//an text box category Name
				$("#txtName").css("display", "none");
				//gan gia tri category Name da nhap cho label
				$("#lblCatName").html(catName);
				//hien thi button submit
				$("#btnSubmit").css("display", "");
				// hien thi button back
				$("#btnback").css("display", "");
				//an button confirm
				$("#btnConfirm").css("display", "none");
				//an button back1
				$("#btnback1").css("display", "none");
				//
				$("#txtTitle1").css("display", "");
				//
				$("#txtTitle").css("display", "none");
			}


		});

		$("#btnback").click(function (event) {
			$("#btnSubmit").css("display", "none");
			$("#btnback").css("display", "none");
			$("#txtName").css("display", "");
			$("#lblCatName").html("");
			$("#btnback1").css("display", "");
			$("#btnConfirm").css("display", "");
			$("#txtTitle1").css("display", "none");
			$("#txtTitle").css("display", "");

		});
	});
</script>
@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}
<h1>h </h1>

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Pages/CategoryCRUD/AddSuccess.cshtml
@page
@model CategoryCRUD_31.Pages.CategoryCRUD.AddSuccessModel
@{
}
<div class="text-center margin-top: 250px">
    <h1 class="display-4">施策カテゴリ編集が完了しました。</h1>
    <button class="btn btn-primary" onclick="window.location.href ='/CategoryCRUD/list'">施策カテゴリ一覧</button>
</div>

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Pages/CategoryCRUD/Edit.cshtml
@page "{CategoryMasterId:int}"
@model CategoryCRUD_31.Pages.CategoryCRUD.EditModel
@{
}
<div>
    <h1 class="mb-5 mt-5" id="txtTitle">施策カテゴリ編集</h1>

    <div　class="mb-5 mt-5" id="txtTitle1" style="display:none">
        <h3>施策カテゴリ追加</h3>
        <h3>以下の施策カテゴリを登録しますか？</h3>
     </div>


<form method="post" id="con" asp-page="Edit">

    <div class="mb-3 mt-5 row" style="display:none">
        <label class="col-form-label col-sm-3">ID​​</label>
        <div class="col-sm-8">
            <input class="form-control" asp-for=" AddCategoryViewModel.CategoryMasterId" readonly />
        </div>
    </div>

    <div class="mb-3 mt-5 row">
        <label class="col-form-label col-sm-2">施策カテゴリ名​​</label>
        <div class="col-sm-8">
            <input class="form-control" id="txtName" type="text" asp-for=" AddCategoryViewModel.CategoryName" aria-required="true" />
            <span asp-validation-for="@Model.AddCategoryViewModel.CategoryName" class="text-danger"></span>
            <label class="lblCatName" id="lblCatName"></label>
        </div>
    </div>


    <div class="col-sm-12 d-flex justify-content-around mt-2">

        <button class="btn btn-primary" type="button" id="btnback" style="display:none">戻る</button>
        <button class="btn btn-primary" type="submit" id="btnSubmit" style="display:none" asp-page-handler="Edit">更新</button>
        <button class="btn btn-primary" type="button" id="btnback1" onclick="window.location.href ='/CategoryCRUD/list'">戻る</button>
        <button class="btn btn-primary" type="button" id="btnConfirm">確認</button>

    </div>
</form>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        //khoi tao bien local
        var catName;
        $("#btnConfirm").click(function (event) {
            var isValid = $("#con").valid()
            if (!isValid) {
                event.preventdefault();

            }
            else {
                //gan gia tri cho bien category Name
                catName = $("#txtName").val();
                //an text box category Name
                $("#txtName").css("display", "none");
                //gan gia tri category Name da nhap cho label
                $("#lblCatName").html(catName);
                //hien thi button submit
                $("#btnSubmit").css("display", "");
                // hien thi button back
                $("#btnback").css("display", "");
                //an button confirm
                $("#btnConfirm").css("display", "none");
                $("#btnback1").css("display", "none");
                $("#txtTitle1").css("display", "");
                $("#txtTitle").css("display", "none");
            }
        });
        $("#btnback").click(function (event) {
            $("#btnSubmit").css("display", "none");
            $("#btnback").css("display", "none");
            $("#txtName").css("display", "");
            $("#lblCatName").html("");
            $("#btnback1").css("display", "");
            $("#btnConfirm").css("display", "");
            $("#txtTitle1").css("display", "none");
            $("#txtTitle").css("display", "");

        });
    });
</script>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Pages/CategoryCRUD/EditSuccess.cshtml
@page
@model CategoryCRUD_31.Pages.CategoryCRUD.EditSuccessModel
@{
}

<div class="text-center margin-top: 250px">
    <h1 class="display-4">施策カテゴリ編集が完了しました。</h1>
    <button class="btn btn-primary" onclick="window.location.href ='/CategoryCRUD/list'">施策カテゴリ一覧へ</button>
</div>

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Pages/CategoryCRUD/List.cshtml
@page
@model CategoryCRUD_31.Pages.CategoryCRUD.ListModel
@{
	int i = 1;
	var pagingmodel = new CategoryCRUD_31.Helpers.PagingModel()
	{
				currenpage = Model.currentPage,
				coutpage = Model.countPage,
				generateUrl = (int? p) => Url.Page("/CategoryCRUD/list", new { p = p })
	};
}



<h1 class="mb-5 mt-5">施策カテゴリ一覧​</h1>

<form method="get" style="text-align:right">

	<input name="SearchCategoryname" value="" />
	<button class="btn btn-primary mb-2" type="submit">検索</button>
</form>

@if (Model.Categories != null && Model.Categories.Any())
{
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>No</th>
				<th>カテゴリー名</th>
				<th></th>
			</tr>
		</thead>
		<tbody>

			@foreach (var category in Model.Categories)
			{
				<tr>
					<td>@(
						i++
						)</td>
					<td>@category.CategoryName</td>
					<td style="text-align :center">
						<a href="/CategoryCRUD/Edit/@category.CategoryMasterId">編集</a>
						<span>|</span>
						<a class="delete-link" data-bs-toggle="modal" data-bs-target="#exampleModal@(category.CategoryMasterId)" href="#">削除</a>
						<div class="modal fade" id="exampleModal@(category.CategoryMasterId)" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
							<div class="modal-dialog">
								<div class="modal-content">
									<div class="modal-header">
										<h1 class="modal-title fs-5" id="exampleModalLabel">削除確認</h1>
										<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
									</div>
									<div class="modal-body">
										<p>@category.CategoryName を削除しても、よろしですか？</p>
										<p>この操作は元に戻せません</p>
									</div>
									<div class="modal-footer">
										<button type="button" class="btn btn-secondary"data-bs-dismiss="modal">閉じる</button>
										<form method="post">
											<input type="hidden" asp-for="AddCategoryViewModel.CategoryMasterId" value="@(category.CategoryMasterId)" />
											<button type="submit" class="btn btn-primary" onclick="deleteid()" asp-page-handler="Delete">削除</button>
										</form>
									</div>
								</div>
							</div>
						</div>
					</td>

				</tr>
			}
		</tbody>

	</table>
}
else
{
	<p> Khong co category nao</p>
}

<partial name="_Paging" model="@pagingmodel" />



<div class="m-5" style="text-align:right">
@*	<a class="btn btn-primary" style="margin-right" asp-page="/CategoryCRUD/AddCategory" >カテゴリー追加</a>*@
	<button class="btn btn-primary"  onclick="window.location.href ='/CategoryCRUD/AddCategory'">カテゴリー追加</button>
</div>

<script>

	function deleteid() {

		alert("施策カテゴリの削除が完了しました。");

	}
</script>

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CategoryCRUD_31</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CategoryCRUD_31.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CategoryCRUD_31</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/CategoryCRUD/List">カテゴリー一覧</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CategoryCRUD_31 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CategoryCRUD_31/CategoryCRUD_31/CategoryCRUD_31/Pages/Shared/_Paging.cshtml
@*
    Model:
      - currentPage:int - Trang hiện tại
      - countPages:int - tổng số trang
      - generateUrl:delegate Func<int?, string> trả về URL tương ứng với trang p (1,2,3 ...)
*@

@model CategoryCRUD_31.Helpers.PagingModel
@{
    int currentPage = Model.currenpage;
    int countPages = Model.coutpage;
    var generateUrl = Model.generateUrl;

    if (currentPage > countPages)
        currentPage = countPages;

    if (countPages <= 1) return;


    int? preview = null;
    int? next = null;

    if (currentPage > 1)
        preview = currentPage - 1;

    if (currentPage < countPages)
        next = currentPage + 1;

    // Các trang hiện thị trong điều hướng
    List<int> pagesRanges = new List<int>();


    int delta = 5;             // Số trang mở rộng về mỗi bên trang hiện tại
    int remain = delta * 2;     // Số trang hai bên trang hiện tại

    pagesRanges.Add(currentPage);
    // Các trang phát triển về hai bên trang hiện tại
    for (int i = 1; i <= delta; i++)
    {
        if (currentPage + i <= countPages)
        {
            pagesRanges.Add(currentPage + i);
            remain--;
        }

        if (currentPage - i >= 1)
        {
            pagesRanges.Insert(0, currentPage - i);
            remain--;
        }

    }
    // Xử lý thêm vào các trang cho đủ remain
    //(xảy ra ở đầu mút của khoảng trang không đủ trang chèn  vào)
    if (remain > 0)
    {
        if (pagesRanges[0] == 1)
        {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.Last() + 1 <= countPages)
                {
                    pagesRanges.Add(pagesRanges.Last() + 1);
                }
            }
        }
        else
        {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.First() - 1 > 1)
                {
                    pagesRanges.Insert(0, pagesRanges.First() - 1);
                }
            }
        }
    }

}

@* PHÁT SINH HTML*@

<ul class="pagination justify-content-center">
    <!-- Previous page link -->
    @if (preview != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(preview)">Prev</a>
        </li>
    }
    else
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Prev</a>
        </li>
    }

    <!-- Numbered page links -->
    @foreach (var pageitem in pagesRanges)
    {
        if (pageitem != currentPage)
        {
            <li class="page-item">
                <a class="page-link" href="@generateUrl(pageitem)">
                    @pageitem
                </a>
            </li>
        }
        else
        {
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">@pageitem <span class="sr-only"></span></a>
            </li>
        }
    }


    <!-- Next page link -->
    @if (next != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(next)">Next</a>
        </li>
    }
    else
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
        </li>
    }
</ul>